- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hrs
  whitelisted: true
  canBeAntag: false
  weight: -10 # HardLight: displayWeight<weight; 10<-10
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-prisoner
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant ] # Frontier
  - !type:GiveItemOnHolidaySpecial # Frontier: even prisoners get a piece of cake (with no file inside).
    holiday: FrontierBirthday # Frontier
    prototype: FrontierBirthdayGift # Frontier

- type: startingGear
  id: PrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetGrey
