- type: entityTable
  id: MercLoot
  table: !type:GroupSelector
    children:
    - id: ClothingBeltWebbingMecranaryTier1Pistol
      weight: 0.5
    - id: ClothingBackpackDuffelMecranaryTier2Revolver
      weight: 0.3
    - id: ClothingBeltWebbingMecranaryTier2Revolver
      weight: 0.3
    - id: ClothingBeltMecranaryTier3Medic
      weight: 0.2
    - id: ClothingBackpackDuffelMecranaryTier3Medic
      weight: 0.2

- type: entityTable
  id: MercLockerLoot
  table: !type:AllSelector
    children:
    - !type:NestedSelector
      tableId: MercLoot
      rolls: !type:RangeNumberSelector
        range: 1, 1
    - !type:NestedSelector
      tableId: MercLoot
      prob: 0.6
      rolls: !type:RangeNumberSelector
        range: 1, 1

- type: entity
  id: LockerMercenaryFilled
  suffix: Filled
  parent: LockerMercenary
  components:
  - type: StorageFill
    contents:
      - id: PinpointerUniversal
      - id: HandHeldMassScanner
      - id: WeaponGrapplingGun
      - id: BoxZiptie

- type: entity
  id: LockerMercenaryWreck
  suffix: WreckFilled
  parent: LockerMercenary
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: MercLockerLoot

- type: entity
  id: LockerNfsdSilverDetectiveFilled
  suffix: Detective, Filled
  parent: LockerNfsdSilver
  components:
  - type: StorageFill
    contents:
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: BoxEvidenceMarkers
      - id: HandLabeler
  - type: AccessReader
    access: [["Detective"]]

- type: entity
  id: NFLockerSecurityFilled
  parent: LockerSecurityFilled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic

- type: entity
  id: NFClosetBombFilled
  parent: ClosetBombFilled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool

- type: entity
  parent: GunSafe
  id: GunSafeTurrets
  name: turret safe
  suffix: ColSec, Filled
  components:
  - type: StorageFill
    contents:
    - id: WeaponCaseHeavyCdet
      amount: 2
    - id: WeaponCaseHeavySlat
      amount: 1
    - id: WeaponCaseHeavyAsmgt
      amount: 1
  - type: AccessReader
    access: [["Security"]]

- type: entity
  parent: GunSafe
  id: GunSafeTurretsCdet
  name: turret safe
  suffix: CDET, Filled
  components:
  - type: StorageFill
    contents:
    - id: WeaponCaseHeavyCdet
      amount: 1
  - type: AccessReader
    access: [["Security"]]
