using System.Numerics;
using Content.Client.Administration.UI.Tabs.ObjectsTab;
using Content.Client.Administration.UI.Tabs.PlayerTab;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    public PlayerTab PlayerTabControl => AdminToolsControl.PlayerTabControl;
    public ObjectsTab ObjectsTabControl => AdminToolsControl.ObjectsTabControl;

    public AdminMenuWindow()
    {
        MinSize = new Vector2(640, 420);
        SetSize = new Vector2(1040, 680);
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
    }

    protected override void Dispose(bool disposing)
    {
        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }
}
