using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.UserInterface;

// Taken from https://github.com/RMC-14/RMC-14
[GenerateTypedNameReferences]
public sealed partial class BlueHorizontalSeparator : Control
{
    public BlueHorizontalSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}
