using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class HorizontalYellowSeparator : Control
{
    public HorizontalYellowSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}
