using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class VerticalYellowSeparator : Control
{
    public VerticalYellowSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}