using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Dialog;

// Taken from https://github.com/RMC-14/RMC-14
[GenerateTypedNameReferences]
public sealed partial class ALDialogWindow : DefaultWindow
{
    public BoxContainer? Container;

    public ALDialogWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
