using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Vore.UI;

[GenerateTypedNameReferences]
public sealed partial class VoreSpaceRow : Control
{
    public Guid Id;

    public VoreSpaceRow()
    {
        RobustXamlLoader.Load(this);
    }
}
