using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Vore.UI;

[GenerateTypedNameReferences]
public sealed partial class VoreControl : Control
{
    public VoreControl()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(SpacesTab, Loc.GetString("al-vore-ui-spaces"));
        TabContainer.SetTabTitle(InsideTab, Loc.GetString("al-vore-ui-inside"));
        TabContainer.SetTabTitle(PreferencesTab, Loc.GetString("al-vore-ui-preferences"));
        TabContainer.SetTabTitle(SpaceContentsTab, Loc.GetString("al-vore-ui-contents"));
        // TabContainer.SetTabTitle(SpaceMessagesTab, Loc.GetString("al-vore-ui-messages")); // TODO AFTERLIGHT
        TabContainer.SetTabTitle(SpaceSettingsTab, Loc.GetString("al-vore-ui-settings"));
        TabContainer.SetTabTitle(SpaceVisualsTab, Loc.GetString("al-vore-ui-visuals"));
    }
}
