using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Vore.UI;

[GenerateTypedNameReferences]
public sealed partial class VorePromptWindow : DefaultWindow
{
    public VorePromptWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

