using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Vore.UI;

[GenerateTypedNameReferences]
public sealed partial class VorePreyView : Control
{
    public VorePreyView()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetEntity(IEntityManager entities, EntityUid ent, EntityUid? player)
    {
        View.SetEntity(ent);
        Label.Text = Identity.Name(ent, entities, player);
    }
}
