using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Vore.UI;

[GenerateTypedNameReferences]
public sealed partial class VoreMessageRow : Control
{
    public VoreMessageRow()
    {
        RobustXamlLoader.Load(this);
    }
}
