using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Vore.UI;

[GenerateTypedNameReferences]
public sealed partial class VoreSettingsRowName : Label
{
    public VoreSettingsRowName()
    {
        RobustXamlLoader.Load(this);
    }
}
