using Content.Shared._Afterlight.Vore;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Afterlight.Vore;

[GenerateTypedNameReferences]
public sealed partial class VoreOverlayButton : Control
{
    public EntProtoId<VoreOverlayComponent> Id { get; set; }

    public VoreOverlayButton()
    {
        RobustXamlLoader.Load(this);
    }
}
