using System.Linq;
using System.Numerics;
using Content.Shared._CD.Silicons;
using Content.Shared._CD.Silicons.Borgs;
using Content.Shared.Silicons.Borgs;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization.TypeSerializers.Implementations;
using Robust.Shared.Utility;

namespace Content.Client._CD.Silicons.Borgs.UI;

[GenerateTypedNameReferences]
public sealed partial class ChassisSpriteSelection : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IResourceCache _resource = default!;

    public BorgSubtypePrototype? SubtypePrototype;
    public event Action? SubtypeSelected;

    public const int PrototypeViewSize = 2;

    public ChassisSpriteSelection()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(BorgTypePrototype borgTypePrototype)
    {
        MainContainer.Visible = true;

        OptionsContainer.RemoveAllChildren();
        // Hardlight start - code simplification
        var buttonGroup = new ButtonGroup();
        List<Button> buttons = new()
        {
            CreateSubtypeButton(
                buttonGroup,
                borgTypePrototype.DummyPrototype,
                "Default",
                null
            )
        };

        foreach (var subtypePrototype in _proto.EnumeratePrototypes<BorgSubtypePrototype>())
        {
            if (subtypePrototype.ParentType != borgTypePrototype.ID)
                continue;

            buttons.Add(CreateSubtypeButton(
                buttonGroup,
                subtypePrototype.DummyPrototype,
                subtypePrototype.Name,
                subtypePrototype
            ));
        }
        // Hardlight end
        foreach (var button in buttons)
        {
            OptionsContainer.AddChild(button);
        }
    }

    // Hardlight start - Code optimization.
    private Button CreateSubtypeButton(
        ButtonGroup group,
        EntProtoId dummyPrototype,
        string labelText,
        BorgSubtypePrototype? subtypePrototype
    )
    {
        var button = new Button
        {
            Group = group,
            MinHeight = 32,
        };

        button.OnPressed += _ =>
        {
            SubtypePrototype = subtypePrototype;
            SubtypeSelected?.Invoke();
        };

        var buttonContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true
        };

        buttonContent.AddChild(CreateEntityPrototypeView(dummyPrototype));
        buttonContent.AddChild(new Label { Text = labelText });

        button.AddChild(buttonContent);

        return button;
    }
    // Hardlight end

    private EntityPrototypeView CreateEntityPrototypeView(EntProtoId entProtoId)
    {
        var entPrototypeView = new EntityPrototypeView();

        entPrototypeView.SetPrototype(entProtoId);
        entPrototypeView.Scale *= PrototypeViewSize;

        return entPrototypeView;
    }
}
