- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  weight: -30 # HardLight
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Maintenance
  - Theatre # Delta V: Add Theatre access
  # - Boxer # Unused for now
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: ClothingHandsGlovesBoxingRigged

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  # storage:
  #   back:
  #   - Stuff
