- type: job
  id: StationTrafficController
  name: job-name-stc
  description: job-description-stc
  playTimeTracker: JobStc
  startingGear: StcGear
  alwaysUseSpawner: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer # HardLight: JobSecurityGuard<JobSecurityOfficer
      time: 10800 # 3 hrs
  canBeAntag: false
  icon: "JobIconStc"
  supervisors: job-supervisors-captain
  weight: 160
  displayWeight: 50 # Second from the top
  setPreference: false # HardLight: true<false
  access:
  - Command # HardLight
  - Service
  - Maintenance
  - External
  - Brig # HardLight
  - Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: StcGear
  equipment:
    id: StcPDA
  storage:
    back:
    - Flash
    - RubberStampStc
    - BoxFolderStc
    - ShipVoucherFrontierStc
