using Content.Client.CrewManifest.UI;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestUiFragment : BoxContainer
{
    public CrewManifestUiFragment()
    {
        RobustXamlLoader.Load(this);

        StationName.AddStyleClass("LabelBig");
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(CrewManifestEntries? entries, string? message = null) // Coyote: Removed name, // HardLight: Added string? & message = null
    {
        CrewManifestListing.DisposeAllChildren();
        CrewManifestListing.RemoveAllChildren();

        StationNameContainer.Visible = entries != null || !string.IsNullOrEmpty(message); // HardLight: Added !string.IsNullOrEmpty(message)
        StationName.Text = string.IsNullOrEmpty(message) ? "Crew Manifest" : message; // HardLight: Rewritten for Coyote compatibility.

        if (entries == null)
            return;

        CrewManifestListing.AddCrewManifestEntries(entries);
    }
}
