using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using Content.Client.Administration.Systems;
using Content.Client.Stylesheets;
using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.Console;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.GameObjects;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class AdminTab : Control
    {
        private enum SubTabIndex
        {
            Quick = 0,
            Votes,
            Ships,
            AHelp,
            Macros,
            Players,
            Objects,
            Statistics,
        }

        private readonly IClientConsoleHost _console;
        private readonly IResourceManager _resources;
        private readonly BwoinkSystem _bwoinkSystem;
        private readonly List<string> _categoryList = new();
        private readonly List<SavedCommandEntry> _savedCommands = new();
        private readonly List<AhelpAdminCategoryState> _ahelpCategories = new();
        private string _currentAutoReplyBotName = string.Empty;
        private string _currentPanicTemplate = string.Empty;
        private AdminStatisticsRoleInfo[] _allRoleSlots = Array.Empty<AdminStatisticsRoleInfo>();

        // UserData paths should be relative for cross-platform compatibility.
        private static readonly ResPath SavedCommandsPath = new("admin_saved_commands.json");

        public AdminTab()
        {
            _console = IoCManager.Resolve<IClientConsoleHost>();
            _resources = IoCManager.Resolve<IResourceManager>();
            _bwoinkSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<BwoinkSystem>();

            try
            {
                RobustXamlLoader.Load(this);
                SubTabs.SetTabTitle((int) SubTabIndex.Quick, Loc.GetString("admin-tools-tab-quick"));
                SubTabs.SetTabTitle((int) SubTabIndex.Votes, Loc.GetString("admin-tools-tab-votes"));
                SubTabs.SetTabTitle((int) SubTabIndex.Ships, Loc.GetString("admin-tools-tab-ships"));
                SubTabs.SetTabTitle((int) SubTabIndex.AHelp, Loc.GetString("admin-tools-tab-ahelp"));
                SubTabs.SetTabTitle((int) SubTabIndex.Macros, Loc.GetString("admin-tools-tab-macros"));
                SubTabs.SetTabTitle((int) SubTabIndex.Players, Loc.GetString("admin-menu-players-tab"));
                SubTabs.SetTabTitle((int) SubTabIndex.Objects, Loc.GetString("admin-menu-objects-tab"));
                SubTabs.SetTabTitle((int) SubTabIndex.Statistics, Loc.GetString("admin-tools-tab-statistics"));
                SubTabs.OnTabChanged += OnSubTabChanged;
                LoadSavedCommands();
                RefreshSavedCommandsList();

                CreateRestartVoteButton.OnPressed += _ => _console.ExecuteCommand("createvote Restart");
                CreatePresetVoteButton.OnPressed += _ => _console.ExecuteCommand("createvote Preset");
                CreateMapVoteButton.OnPressed += _ => _console.ExecuteCommand("createvote Map");
                CreateCustomVoteButton.OnPressed += _ => CreateCustomVote();
                CancelVoteButton.OnPressed += _ => CancelVote();
                VoteAuditOpenButton.OnPressed += _ => OpenVoteAudit();

                SaveShipButton.OnPressed += _ => SaveShip();

                RefreshAhelpConfigButton.OnPressed += _ => _bwoinkSystem.RequestAhelpAdminConfig();
                SaveAutoReplyBotNameButton.OnPressed += _ => SaveAutoReplyBotName();
                AddCategoryButton.OnPressed += _ => AddOrRestoreCategory();
                RemoveCategoryButton.OnPressed += _ => RemoveCategory();
                AutoReplyEnableButton.OnPressed += _ => _bwoinkSystem.SetAhelpAutoReplyEnabled(true);
                AutoReplyDisableButton.OnPressed += _ => _bwoinkSystem.SetAhelpAutoReplyEnabled(false);
                AutoReplyRuleEnableButton.OnPressed += _ => SetAutoReplyRuleEnabled(true);
                AutoReplyRuleDisableButton.OnPressed += _ => SetAutoReplyRuleEnabled(false);
                AutoReplySaveButton.OnPressed += _ => SaveAutoReplyTemplate();
                AutoReplyResetButton.OnPressed += _ => ResetAutoReplyTemplate();
                PanicEnableButton.OnPressed += _ => _bwoinkSystem.SetAhelpPanicAutoReplyEnabled(true);
                PanicDisableButton.OnPressed += _ => _bwoinkSystem.SetAhelpPanicAutoReplyEnabled(false);
                PanicSaveButton.OnPressed += _ => SavePanicTemplate();

                TriageEnableButton.OnPressed += _ => _bwoinkSystem.SetAhelpTriageEnabled(true);
                TriageDisableButton.OnPressed += _ => _bwoinkSystem.SetAhelpTriageEnabled(false);
                TriageRuleEnableButton.OnPressed += _ => SetTriageRuleEnabled(true);
                TriageRuleDisableButton.OnPressed += _ => SetTriageRuleEnabled(false);
                TriageSaveButton.OnPressed += _ => SaveTriageKeywords();
                TriageResetButton.OnPressed += _ => ResetTriageKeywords();

                RefreshStatisticsButton.OnPressed += _ => RefreshStatistics();
                RolesSearchBox.OnTextChanged += _ => ApplyRolesFilter();
                _bwoinkSystem.AdminStatisticsReceived += UpdateStatistics;

                SavedCommandRunButton.OnPressed += _ => RunSavedCommand();
                SavedCommandSaveButton.OnPressed += _ => SaveSavedCommand();
                SharedMacrosButton.OnPressed += _ => OpenSharedMacroWindow();
                SavedCommandDeleteButton.OnPressed += _ => DeleteSavedCommand();
                SavedCommandsList.OnItemSelected += args => OnSavedCommandSelected(args.ItemIndex);
                AutoReplyCategory.OnItemSelected += args => OnAhelpCategorySelected(args.Id);
                AutoReplyTemplatesList.OnItemSelected += args => OnAutoReplyCategoryListSelected(args.ItemIndex);
                TriageRulesList.OnItemSelected += args => OnTriageCategoryListSelected(args.ItemIndex);
                _bwoinkSystem.AhelpAdminConfigUpdated += UpdateAhelpConfig;
                _bwoinkSystem.SharedAdminMacrosUpdated += UpdateSharedAdminMacros;

                UpdateSavedCommandButtons();
                UpdateCustomVoteButton();
                UpdateCancelVoteButton();
                UpdateSaveShipButton();
                UpdateAhelpEditorButtons();

                SavedCommandName.OnTextChanged += _ => UpdateSavedCommandButtons();
                SavedCommandText.OnTextChanged += _ => UpdateSavedCommandButtons();
                CustomVoteTitle.OnTextChanged += _ => UpdateCustomVoteButton();
                CustomVoteOptions.OnTextChanged += _ => UpdateCustomVoteButton();
                CancelVoteId.OnTextChanged += _ => UpdateCancelVoteButton();
                ShipDeedId.OnTextChanged += _ => UpdateSaveShipButton();
                AutoReplyBotName.OnTextChanged += _ => UpdateAhelpEditorButtons();
                AhelpCategoryName.OnTextChanged += _ => UpdateAhelpEditorButtons();
                AutoReplyTemplate.OnTextChanged += _ => UpdateAhelpEditorButtons();
                PanicTemplate.OnTextChanged += _ => UpdateAhelpEditorButtons();
                TriageKeywords.OnTextChanged += _ => UpdateAhelpEditorButtons();

                if (_bwoinkSystem.CurrentAhelpAdminConfig != null)
                    UpdateAhelpConfig(_bwoinkSystem.CurrentAhelpAdminConfig);
                else
                    _bwoinkSystem.RequestAhelpAdminConfig();

                RefreshStatistics();
            }
            catch (System.Exception)
            {
                _console.WriteError(null, "AdminTab failed to initialize completely. Some controls may be unavailable this session.");
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                SubTabs.OnTabChanged -= OnSubTabChanged;
                _bwoinkSystem.AhelpAdminConfigUpdated -= UpdateAhelpConfig;
                _bwoinkSystem.SharedAdminMacrosUpdated -= UpdateSharedAdminMacros;
                _bwoinkSystem.AdminStatisticsReceived -= UpdateStatistics;
                RolesSearchBox.OnTextChanged -= _ => ApplyRolesFilter();
            }
        }

        private void OnSubTabChanged(int tabIndex)
        {
            if ((SubTabIndex) tabIndex == SubTabIndex.Objects)
                ObjectsTabControl.RefreshObjectList();

            if ((SubTabIndex) tabIndex == SubTabIndex.Statistics)
                RefreshStatistics();
        }

        private void RefreshStatistics()
        {
            StatisticsUpdatedLabel.Text = Loc.GetString("admin-tools-statistics-updated-loading");
            _bwoinkSystem.RequestAdminStatistics();
        }

        private void UpdateStatistics(AdminStatisticsResponseMessage message)
        {
            if (!string.IsNullOrEmpty(message.Error) || message.Snapshot == null)
            {
                StatisticsOnlineLabel.Text = Loc.GetString("admin-tools-statistics-error");
                StatisticsLagLabel.Text = string.Empty;
                StatisticsRoundLabel.Text = string.Empty;
                StatisticsUptimeLabel.Text = string.Empty;
                StatisticsRolesList.Clear();
                StatisticsAntagsList.Clear();
                StatisticsUpdatedLabel.Text = Loc.GetString("admin-tools-statistics-updated-error");
                return;
            }

            var snapshot = message.Snapshot;
            StatisticsOnlineLabel.Text = Loc.GetString("admin-tools-statistics-online-value", ("count", snapshot.OnlinePlayers));
            StatisticsLagLabel.Text = Loc.GetString(
                "admin-tools-statistics-lag-value",
                ("avg", snapshot.AveragePingMs),
                ("max", snapshot.MaxPingMs),
                ("high", snapshot.HighPingPlayers));
            StatisticsRoundLabel.Text = Loc.GetString(
                "admin-tools-statistics-round-value",
                ("roundId", snapshot.RoundId),
                ("runLevel", snapshot.RunLevel),
                ("duration", FormatDuration(snapshot.RoundDuration)));
            StatisticsUptimeLabel.Text = Loc.GetString(
                "admin-tools-statistics-uptime-value",
                ("uptime", FormatDuration(snapshot.ServerUptime)));

            _allRoleSlots = snapshot.RoleSlots;
            RolesSearchBox.Clear();
            ApplyRolesFilter();

            StatisticsAntagsList.Clear();
            if (snapshot.Antags.Length == 0)
            {
                StatisticsAntagsList.AddItem(Loc.GetString("admin-tools-statistics-antags-none"));
            }
            else
            {
                foreach (var antag in snapshot.Antags)
                {
                    StatisticsAntagsList.AddItem(antag);
                }
            }

            StatisticsUpdatedLabel.Text = Loc.GetString(
                "admin-tools-statistics-updated-now",
                ("time", DateTime.Now.ToString("HH:mm:ss")));
        }

        private static string FormatDuration(TimeSpan duration)
        {
            var totalHours = (int) duration.TotalHours;
            return $"{totalHours:00}:{duration.Minutes:00}:{duration.Seconds:00}";
        }

        private void ApplyRolesFilter()
        {
            var searchText = RolesSearchBox.Text.Trim().ToLowerInvariant();
            StatisticsRolesList.Clear();

            foreach (var role in _allRoleSlots)
            {
                // Filter by search text
                if (!string.IsNullOrEmpty(searchText) && 
                    !role.RoleName.ToLowerInvariant().Contains(searchText))
                    continue;

                var roleText = role.OpenSlots == null
                    ? Loc.GetString(
                        "admin-tools-statistics-role-unlimited",
                        ("name", role.RoleName),
                        ("taken", role.TakenSlots))
                    : Loc.GetString(
                        "admin-tools-statistics-role-finite",
                        ("name", role.RoleName),
                        ("taken", role.TakenSlots),
                        ("open", role.OpenSlots.Value));

                StatisticsRolesList.AddItem(roleText);
            }
        }

        private void UpdateSavedCommandButtons()
        {
            var hasName = SavedCommandName.Text.Trim().Length > 0;
            var hasCommand = Rope.Collapse(SavedCommandText.TextRope).Trim().Length > 0;
            SavedCommandSaveButton.Disabled = !(hasName && hasCommand);
            SavedCommandRunButton.Disabled = !hasCommand && GetSelectedSavedIndex() < 0;
            SavedCommandDeleteButton.Disabled = GetSelectedSavedIndex() < 0 && !hasName;
        }

        private void UpdateCustomVoteButton()
        {
            var hasTitle = CustomVoteTitle.Text.Trim().Length > 0;
            var optionCount = CustomVoteOptions.Text
                .Split(';')
                .Count(x => x.Trim().Length > 0);
            CreateCustomVoteButton.Disabled = !(hasTitle && optionCount >= 2);
        }

        private void UpdateCancelVoteButton()
        {
            CancelVoteButton.Disabled = CancelVoteId.Text.Trim().Length == 0;
        }


        private void UpdateSaveShipButton()
        {
            SaveShipButton.Disabled = ShipDeedId.Text.Trim().Length == 0;
        }

        private void UpdateAhelpEditorButtons()
        {
            var selectedCategory = SelectedCategoryState();
            var hasSelectedCategory = selectedCategory != null;
            var botName = AutoReplyBotName.Text.Trim();
            var hasCategoryName = AhelpCategoryName.Text.Trim().Length > 0;
            var hasTemplate = Rope.Collapse(AutoReplyTemplate.TextRope).Trim().Length > 0;
            var panicTemplate = Rope.Collapse(PanicTemplate.TextRope).Trim();
            var hasKeywords = Rope.Collapse(TriageKeywords.TextRope).Trim().Length > 0;

            SaveAutoReplyBotNameButton.Disabled = botName.Length == 0 || string.Equals(botName, _currentAutoReplyBotName, StringComparison.Ordinal);
            AddCategoryButton.Disabled = !(hasCategoryName && hasTemplate && hasKeywords);
            RemoveCategoryButton.Disabled = !hasSelectedCategory;
            AutoReplySaveButton.Disabled = !(hasSelectedCategory && hasTemplate);
            AutoReplyResetButton.Disabled = !hasSelectedCategory;
            AutoReplyRuleEnableButton.Disabled = selectedCategory is not { HasAutoReply: true } || selectedCategory.AutoReplyEnabled;
            AutoReplyRuleDisableButton.Disabled = selectedCategory is not { HasAutoReply: true } || !selectedCategory.AutoReplyEnabled;
            TriageSaveButton.Disabled = !(hasSelectedCategory && hasKeywords);
            TriageResetButton.Disabled = !hasSelectedCategory;
            TriageRuleEnableButton.Disabled = selectedCategory is not { HasTriage: true } || selectedCategory.TriageEnabled;
            TriageRuleDisableButton.Disabled = selectedCategory is not { HasTriage: true } || !selectedCategory.TriageEnabled;
            PanicSaveButton.Disabled = panicTemplate.Length == 0 || string.Equals(panicTemplate, _currentPanicTemplate, StringComparison.Ordinal);
        }

        private void UpdateAhelpConfig(AhelpAdminConfigState state)
        {
            var currentCategory = SelectedCategory();

            _ahelpCategories.Clear();
            _ahelpCategories.AddRange(state.Categories.OrderBy(category => category.Name));
            _currentAutoReplyBotName = state.AutoReplyBotName;
            _currentPanicTemplate = state.PanicAutoReplyTemplate;

            RefreshCategoryOptions(currentCategory);
            RefreshAutoReplyList();
            RefreshTriageList();
            ApplyToggleState(AutoReplyEnableButton, AutoReplyDisableButton, state.AutoReplyEnabled);
            ApplyToggleState(TriageEnableButton, TriageDisableButton, state.TriageEnabled);
            ApplyToggleState(PanicEnableButton, PanicDisableButton, state.PanicAutoReplyEnabled);
            AutoReplyBotName.Text = state.AutoReplyBotName;
            PanicTemplate.TextRope = new Rope.Leaf(state.PanicAutoReplyTemplate);

            AutoReplyStateLabel.Text = Loc.GetString(
                state.AutoReplyEnabled
                    ? "admin-tools-ahelp-state-enabled"
                    : "admin-tools-ahelp-state-disabled");
            AutoReplyStateLabel.FontColorOverride = state.AutoReplyEnabled ? Color.LimeGreen : Color.Red;

            TriageStateLabel.Text = Loc.GetString(
                state.TriageEnabled
                    ? "admin-tools-triage-state-enabled"
                    : "admin-tools-triage-state-disabled");
            TriageStateLabel.FontColorOverride = state.TriageEnabled ? Color.LimeGreen : Color.Red;

            PanicStateLabel.Text = Loc.GetString(
                state.PanicAutoReplyEnabled
                    ? "admin-tools-panic-state-enabled"
                    : "admin-tools-panic-state-disabled");
            PanicStateLabel.FontColorOverride = state.PanicAutoReplyEnabled ? Color.LimeGreen : Color.Red;

            SyncSelectedCategoryEditors();
            UpdateAhelpEditorButtons();
        }

        private void RefreshCategoryOptions(string? preferredCategory)
        {
            _categoryList.Clear();
            AutoReplyCategory.Clear();

            foreach (var category in _ahelpCategories)
            {
                _categoryList.Add(category.Name);
                AutoReplyCategory.AddItem(category.Name, _categoryList.Count - 1);
            }

            if (_categoryList.Count == 0)
                return;

            var preferredIndex = preferredCategory == null
                ? 0
                : _categoryList.FindIndex(category => string.Equals(category, preferredCategory, StringComparison.OrdinalIgnoreCase));

            AutoReplyCategory.SelectId(preferredIndex >= 0 ? preferredIndex : 0);
        }

        private void RefreshAutoReplyList()
        {
            AutoReplyTemplatesList.Clear();
            foreach (var category in _ahelpCategories.Where(category => category.HasAutoReply))
            {
                var suffix = category.IsDefault ? string.Empty : Loc.GetString("admin-tools-ahelp-custom-tag");
                var enabledTag = category.AutoReplyEnabled
                    ? Loc.GetString("admin-tools-ahelp-enabled-tag")
                    : Loc.GetString("admin-tools-ahelp-disabled-tag");
                AutoReplyTemplatesList.AddItem($"{category.Name}{suffix}{enabledTag}  -  {TrimPreview(category.Template)}");
            }
        }

        private void RefreshTriageList()
        {
            TriageRulesList.Clear();
            foreach (var category in _ahelpCategories.Where(category => category.HasTriage))
            {
                var suffix = category.IsDefault ? string.Empty : Loc.GetString("admin-tools-ahelp-custom-tag");
                var enabledTag = category.TriageEnabled
                    ? Loc.GetString("admin-tools-ahelp-enabled-tag")
                    : Loc.GetString("admin-tools-ahelp-disabled-tag");
                TriageRulesList.AddItem($"{category.Name}{suffix}{enabledTag}  -  {TrimPreview(category.Keywords)}");
            }
        }

        private static string TrimPreview(string value)
        {
            var trimmed = value.Replace('\n', ' ').Trim();
            return trimmed.Length <= 80 ? trimmed : trimmed[..77] + "...";
        }

        private void ApplyToggleState(Button enableButton, Button disableButton, bool enabled)
        {
            enableButton.Pressed = enabled;
            disableButton.Pressed = !enabled;

            if (enabled)
                enableButton.AddStyleClass(StyleNano.StyleClassButtonColorGreen);
            else
                enableButton.RemoveStyleClass(StyleNano.StyleClassButtonColorGreen);

            disableButton.ModulateSelfOverride = enabled ? null : Color.Red;
        }

        private string? SelectedCategory()
        {
            if (_categoryList.Count == 0)
                return null;

            var selected = AutoReplyCategory.SelectedId;
            if (selected < 0 || selected >= _categoryList.Count)
                return null;

            return _categoryList[selected];
        }

        private AhelpAdminCategoryState? SelectedCategoryState()
        {
            var category = SelectedCategory();
            return category == null
                ? null
                : _ahelpCategories.FirstOrDefault(entry => string.Equals(entry.Name, category, StringComparison.OrdinalIgnoreCase));
        }

        private void OnAhelpCategorySelected(int id)
        {
            if (id < 0 || id >= _categoryList.Count)
                return;

            // OptionButton.ButtonOnPressed fires OnItemSelected without calling Select(),
            // so SelectedId is not updated on user interaction. Commit the selection here
            // so SyncSelectedCategoryEditors reads the correct category.
            AutoReplyCategory.SelectId(id);
            SyncSelectedCategoryEditors();
        }

        private void OnAutoReplyCategoryListSelected(int index)
        {
            var category = _ahelpCategories.Where(entry => entry.HasAutoReply).ElementAtOrDefault(index);
            SelectCategory(category?.Name);
        }

        private void OnTriageCategoryListSelected(int index)
        {
            var category = _ahelpCategories.Where(entry => entry.HasTriage).ElementAtOrDefault(index);
            SelectCategory(category?.Name);
        }

        private void SelectCategory(string? categoryName)
        {
            if (categoryName == null)
                return;

            var index = _categoryList.FindIndex(category => string.Equals(category, categoryName, StringComparison.OrdinalIgnoreCase));
            if (index < 0)
                return;

            AutoReplyCategory.SelectId(index);
            SyncSelectedCategoryEditors();
        }

        private void SyncSelectedCategoryEditors()
        {
            var category = SelectedCategoryState();

            if (category == null)
            {
                AhelpCategoryName.Text = string.Empty;
                AutoReplyTemplate.TextRope = Rope.Leaf.Empty;
                TriageKeywords.TextRope = Rope.Leaf.Empty;
                AutoReplyRuleStateLabel.Text = Loc.GetString("admin-tools-ahelp-rule-state-unselected");
                AutoReplyRuleStateLabel.FontColorOverride = null;
                TriageRuleStateLabel.Text = Loc.GetString("admin-tools-triage-rule-state-unselected");
                TriageRuleStateLabel.FontColorOverride = null;
                UpdateAhelpEditorButtons();
                return;
            }

            AhelpCategoryName.Text = category.Name;
            AutoReplyTemplate.TextRope = new Rope.Leaf(category.Template);
            TriageKeywords.TextRope = new Rope.Leaf(category.Keywords);
            AutoReplyRuleStateLabel.Text = Loc.GetString(
                category.AutoReplyEnabled
                    ? "admin-tools-ahelp-rule-state-enabled-category"
                    : "admin-tools-ahelp-rule-state-disabled-category",
                ("category", category.Name));
            AutoReplyRuleStateLabel.FontColorOverride = category.AutoReplyEnabled ? Color.LimeGreen : Color.Red;
            TriageRuleStateLabel.Text = Loc.GetString(
                category.TriageEnabled
                    ? "admin-tools-triage-rule-state-enabled-category"
                    : "admin-tools-triage-rule-state-disabled-category",
                ("category", category.Name));
            TriageRuleStateLabel.FontColorOverride = category.TriageEnabled ? Color.LimeGreen : Color.Red;
            UpdateAhelpEditorButtons();
        }

        private void CreateCustomVote()
        {
            var title = CustomVoteTitle.Text.Trim();
            if (title.Length == 0)
                return;

            var options = CustomVoteOptions.Text
                .Split(';')
                .Select(x => x.Trim())
                .Where(x => x.Length > 0)
                .ToArray();

            if (options.Length < 2)
                return;

            var escapedTitle = CommandParsing.Escape(title);
            var escapedOptions = string.Join(" ", options.Select(x => $"\"{CommandParsing.Escape(x)}\""));
            _console.ExecuteCommand($"customvote \"{escapedTitle}\" {escapedOptions}");
        }

        private void CancelVote()
        {
            var voteId = CancelVoteId.Text.Trim();
            if (voteId.Length == 0)
                return;

            _console.ExecuteCommand($"cancelvote {voteId}");
        }

        private Content.Client.Administration.UI.Voting.VoteAuditWindow? _voteAuditWindow;

        private void OpenVoteAudit()
        {
            if (_voteAuditWindow == null || _voteAuditWindow.Disposed || !_voteAuditWindow.IsOpen)
            {
                _voteAuditWindow = new Content.Client.Administration.UI.Voting.VoteAuditWindow();
                _voteAuditWindow.OpenCentered();
            }
            else
            {
                _voteAuditWindow.MoveToFront();
            }
        }

        private void SaveShip()
        {
            var deedId = ShipDeedId.Text.Trim();
            if (deedId.Length == 0)
                return;

            _console.ExecuteCommand($"saveship {deedId}");
        }

        private void AddOrRestoreCategory()
        {
            var category = AhelpCategoryName.Text.Trim();
            var template = Rope.Collapse(AutoReplyTemplate.TextRope).Trim();
            var keywords = Rope.Collapse(TriageKeywords.TextRope).Trim();

            if (category.Length == 0 || template.Length == 0 || keywords.Length == 0)
                return;

            _bwoinkSystem.AddOrRestoreAhelpCategory(category, template, keywords);
        }

        private void SaveAutoReplyBotName()
        {
            var botName = AutoReplyBotName.Text.Trim();
            if (botName.Length == 0)
                return;

            _bwoinkSystem.SetAhelpAutoReplyBotName(botName);
        }

        private void SaveAutoReplyTemplate()
        {
            if (SelectedCategory() is not { } category)
                return;

            var template = Rope.Collapse(AutoReplyTemplate.TextRope).Trim();
            if (template.Length == 0)
                return;

            _bwoinkSystem.SetAhelpAutoReplyTemplate(category, template);
        }

        private void SetAutoReplyRuleEnabled(bool enabled)
        {
            if (SelectedCategory() is not { } category)
                return;

            _bwoinkSystem.SetAhelpCategoryAutoReplyEnabled(category, enabled);
        }

        private void ResetAutoReplyTemplate()
        {
            if (SelectedCategory() is not { } category)
                return;

            _bwoinkSystem.ResetAhelpAutoReplyTemplate(category);
        }

        private void SaveTriageKeywords()
        {
            if (SelectedCategory() is not { } category)
                return;

            var keywords = Rope.Collapse(TriageKeywords.TextRope).Trim();
            if (keywords.Length == 0)
                return;

            _bwoinkSystem.SetAhelpTriageKeywords(category, keywords);
        }

        private void SetTriageRuleEnabled(bool enabled)
        {
            if (SelectedCategory() is not { } category)
                return;

            _bwoinkSystem.SetAhelpCategoryTriageEnabled(category, enabled);
        }

        private void ResetTriageKeywords()
        {
            if (SelectedCategory() is not { } category)
                return;

            _bwoinkSystem.ResetAhelpTriageKeywords(category);
        }

        private void SavePanicTemplate()
        {
            var template = Rope.Collapse(PanicTemplate.TextRope).Trim();
            if (template.Length == 0)
                return;

            _bwoinkSystem.SetAhelpPanicAutoReplyTemplate(template);
        }

        private void RemoveCategory()
        {
            if (SelectedCategory() is not { } category)
                return;

            _bwoinkSystem.RemoveAhelpCategory(category);
        }

        // ---- Saved console commands (persisted locally per user) ----

        private sealed class SavedCommandEntry
        {
            public string Name { get; set; } = string.Empty;
            public string Command { get; set; } = string.Empty;
        }

        private SharedMacroWindow? _sharedMacroWindow;

        private void OpenSharedMacroWindow()
        {
            if (_sharedMacroWindow == null || _sharedMacroWindow.Disposed || !_sharedMacroWindow.IsOpen)
            {
                _sharedMacroWindow = new SharedMacroWindow();
                _sharedMacroWindow.OnClose += () => _sharedMacroWindow = null;
                _sharedMacroWindow.RefreshRequested += () => _bwoinkSystem.RequestSharedAdminMacros();
                _sharedMacroWindow.CopySelectedToLocalRequested += CopySharedMacroToLocal;
                _sharedMacroWindow.CopyLocalToSharedRequested += CopyLocalMacroToShared;
                _sharedMacroWindow.DeleteSharedRequested += DeleteSelectedSharedMacro;
                _sharedMacroWindow.UpdateMacros(_bwoinkSystem.CurrentSharedAdminMacros);
                _sharedMacroWindow.OpenCentered();
            }
            else
            {
                _sharedMacroWindow.MoveToFront();
            }

            _bwoinkSystem.RequestSharedAdminMacros();
        }

        private void UpdateSharedAdminMacros(SharedAdminMacroState[] macros)
        {
            _sharedMacroWindow?.UpdateMacros(macros);
        }

        private void CopySharedMacroToLocal()
        {
            if (_sharedMacroWindow?.SelectedMacro is not { } macro)
                return;

            SavedCommandName.Text = macro.Name;
            SavedCommandText.TextRope = new Rope.Leaf(macro.Command);
            UpdateSavedCommandButtons();
        }

        private void CopyLocalMacroToShared()
        {
            var name = SavedCommandName.Text.Trim();
            var command = Rope.Collapse(SavedCommandText.TextRope).Trim();
            if (name.Length == 0 || command.Length == 0)
                return;

            _bwoinkSystem.UpsertSharedAdminMacro(name, command);
        }

        private void DeleteSelectedSharedMacro()
        {
            if (_sharedMacroWindow?.SelectedMacro is not { } macro)
                return;

            _bwoinkSystem.DeleteSharedAdminMacro(macro.Name);
        }

        private static string EscapeSavedValue(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }

        private static string UnescapeSavedValue(string value)
        {
            var chars = new List<char>(value.Length);
            var escaping = false;

            foreach (var ch in value)
            {
                if (!escaping)
                {
                    if (ch == '\\')
                    {
                        escaping = true;
                        continue;
                    }

                    chars.Add(ch);
                    continue;
                }

                chars.Add(ch switch
                {
                    'r' => '\r',
                    'n' => '\n',
                    't' => '\t',
                    '\\' => '\\',
                    _ => ch,
                });

                escaping = false;
            }

            if (escaping)
                chars.Add('\\');

            return new string(chars.ToArray());
        }

        private static bool TryParseSavedCommand(string line, out SavedCommandEntry? entry)
        {
            entry = null;

            var separator = line.IndexOf('\t');
            if (separator <= 0 || separator >= line.Length - 1)
                return false;

            var name = UnescapeSavedValue(line[..separator]);
            var command = UnescapeSavedValue(line[(separator + 1)..]);

            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(command))
                return false;

            entry = new SavedCommandEntry
            {
                Name = name,
                Command = command,
            };

            return true;
        }

        private void RunSavedCommand()
        {
            var selected = GetSelectedSavedIndex();
            if (selected >= 0)
            {
                RunSavedCommandAt(selected);
                return;
            }

            var command = Rope.Collapse(SavedCommandText.TextRope).Trim();
            if (command.Length == 0)
                return;

            RunCommandSequence(command);
        }

        private void SaveSavedCommand()
        {
            var name = SavedCommandName.Text.Trim();
            var command = Rope.Collapse(SavedCommandText.TextRope).Trim();
            if (name.Length == 0 || command.Length == 0)
                return;

            var existing = FindSavedIndex(name);
            if (existing >= 0)
                _savedCommands[existing].Command = command;
            else
                _savedCommands.Add(new SavedCommandEntry { Name = name, Command = command });

            PersistSavedCommands();
            RefreshSavedCommandsList();
            UpdateSavedCommandButtons();
        }

        private void DeleteSavedCommand()
        {
            var selected = GetSelectedSavedIndex();
            if (selected < 0)
            {
                // Fall back to matching by name field if nothing is selected.
                var name = SavedCommandName.Text.Trim();
                if (name.Length == 0)
                    return;
                selected = FindSavedIndex(name);
                if (selected < 0)
                    return;
            }

            _savedCommands.RemoveAt(selected);
            PersistSavedCommands();
            RefreshSavedCommandsList();
            UpdateSavedCommandButtons();
        }

        private void RefreshSavedCommandsList()
        {
            SavedCommandsList.Clear();
            foreach (var entry in _savedCommands)
            {
                SavedCommandsList.AddItem($"{entry.Name}  -  {entry.Command}");
            }
        }

        private int GetSelectedSavedIndex()
        {
            var selected = SavedCommandsList.GetSelected().FirstOrDefault();
            if (selected == null)
                return -1;
            return SavedCommandsList.IndexOf(selected);
        }

        private void OnSavedCommandSelected(int index)
        {
            if (index < 0 || index >= _savedCommands.Count)
                return;

            var selected = _savedCommands[index];
            SavedCommandName.Text = selected.Name;
            SavedCommandText.TextRope = new Rope.Leaf(selected.Command);
            UpdateSavedCommandButtons();
        }

        private int FindSavedIndex(string name)
        {
            for (var i = 0; i < _savedCommands.Count; i++)
            {
                if (string.Equals(_savedCommands[i].Name, name, System.StringComparison.OrdinalIgnoreCase))
                    return i;
            }
            return -1;
        }

        private void LoadSavedCommands()
        {
            _savedCommands.Clear();

            try
            {
                if (!_resources.UserData.Exists(SavedCommandsPath))
                    return;

                using var reader = _resources.UserData.OpenText(SavedCommandsPath);
                while (true)
                {
                    var line = reader.ReadLine();
                    if (line == null)
                        break;

                    if (string.IsNullOrWhiteSpace(line))
                        continue;

                    if (!TryParseSavedCommand(line, out var entry) || entry == null)
                        continue;

                    _savedCommands.Add(entry);
                }

                if (_savedCommands.Count > 0)
                    return;
            }
            catch (IOException)
            {
                // Ignore read errors, treat as empty list.
            }
            catch (System.Exception)
            {
                // Invalid/unsupported path or provider-specific read errors: treat as empty list.
            }
        }

        private void PersistSavedCommands()
        {
            try
            {
                using var writer = _resources.UserData.OpenWriteText(SavedCommandsPath);

                foreach (var entry in _savedCommands)
                {
                    var name = EscapeSavedValue(entry.Name);
                    var command = EscapeSavedValue(entry.Command);
                    writer.WriteLine($"{name}\t{command}");
                }
            }
            catch (IOException)
            {
                // Best-effort save; surface via console for the admin.
                _console.WriteError(null, Loc.GetString("admin-tools-saved-write-error"));
            }
            catch (System.Exception)
            {
                _console.WriteError(null, Loc.GetString("admin-tools-saved-write-error"));
            }
        }

        private void RunSavedCommandAt(int index)
        {
            if (index < 0 || index >= _savedCommands.Count)
                return;

            RunCommandSequence(_savedCommands[index].Command);
        }

        private void RunCommandSequence(string commandBlock)
        {
            foreach (var command in commandBlock
                         .Split('\n')
                         .Select(line => line.Trim())
                         .Where(line => line.Length > 0))
            {
                _console.ExecuteCommand(command);
            }
        }
    }
}
