using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AdminToolsWindow : DefaultWindow
{
    public AdminToolsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
