using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Afterlight.Subtle;

[GenerateTypedNameReferences]
public sealed partial class SubtleWindow : DefaultWindow
{
    public SubtleWindow()
    {
        RobustXamlLoader.Load(this);
        TextEdit.Placeholder = new Rope.Leaf(Loc.GetString("al-subtle-type-something"));
    }
}
