using System.Collections.Immutable;
using Content.Shared.Database._Afterlight;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksButtons : Control
{
    public readonly ImmutableArray<(Button Button, KinkPreference Preference)> AllButtons;
    public Action<ButtonEventArgs, KinkPreference>? OnPressed;

    public KinksButtons()
    {
        RobustXamlLoader.Load(this);

        AllButtons = ImmutableArray.Create(
            (FavouriteButton, KinkPreference.Favourite),
            (YesButton, KinkPreference.Yes),
            (AskButton, KinkPreference.Ask),
            (NoButton, KinkPreference.No)
        );

        foreach (var (button, preference) in AllButtons)
        {
            button.OnPressed += args => OnPressed?.Invoke(args, preference);
        }
    }

    public void SetPreference(KinkPreference? setPreference)
    {
        foreach (var (button, buttonPreference) in AllButtons)
        {
            button.Pressed = buttonPreference == setPreference;
        }
    }
}
