using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksListColumn : Control
{
    public KinksListColumn()
    {
        RobustXamlLoader.Load(this);
    }
}
