using Content.Shared._Afterlight.Kinks;
using Content.Shared.Database._Afterlight;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksRow : Control
{
    public EntProtoId<KinkDefinitionComponent>? KinkId;
    public event Action<ButtonEventArgs, KinkPreference>? OnPressed;

    public KinksRow()
    {
        RobustXamlLoader.Load(this);

        Buttons.OnPressed += (args, preference) => OnPressed?.Invoke(args, preference);
    }

    public void SetIcon(KinkPreference? preference)
    {
        var symbol = preference switch
        {
            KinkPreference.No => "X",
            KinkPreference.Ask => "?",
            KinkPreference.Yes => "✓",
            KinkPreference.Favourite => "❤",
            _ => " "
        };

        var color = preference.GetColor();
        IconLabel.Text = $"[color={color.ToHex()}]{symbol}[/color]";
    }

    public void SetPreference(KinkPreference? preference)
    {
        SetIcon(preference);
        Buttons.SetPreference(preference);
    }
}
