using Content.Shared._Afterlight.Collections;
using Content.Shared._Afterlight.Kinks;
using Content.Shared.Database._Afterlight;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksListWindow : DefaultWindow
{
    public KinksListWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public IEnumerable<KinksListLabel> GetKinks()
    {
        foreach (var columnChild in Columns.Children)
        {
            if (columnChild is not KinksListColumn column)
                continue;

            foreach (var kinkChild in column.KinksContainer.Children)
            {
                if (kinkChild is not KinksListLabel label)
                    continue;

                yield return label;
            }
        }
    }

    public void ResetKinksColor()
    {
        foreach (var label in GetKinks())
        {
            label.Label.Modulate = Color.White;
        }
    }

    public void ResetKinksVisibility()
    {
        foreach (var label in GetKinks())
        {
            label.Visible = true;
        }
    }

    public void FilterKinks(
        IReadOnlyDictionary<EntProtoId<KinkDefinitionComponent>, KinkPreference>? localKinks,
        IReadOnlyDictionary<EntProtoId<KinkDefinitionComponent>, KinkPreference> otherKinks)
    {
        if (localKinks == null)
        {
            ResetKinksVisibility();
            return;
        }

        var search = SearchEdit.Text;
        foreach (var label in GetKinks())
        {
            if (label is not { Label.Text: { } labelText, KinkId: { } kinkId })
                continue;

            var matchesSearch = string.IsNullOrWhiteSpace(search) ||
                                labelText.Contains(search, StringComparison.OrdinalIgnoreCase);
            var matchesMatching = !OnlyShowMatchingButton.Pressed || MatchesMatching(localKinks, otherKinks, kinkId);
            label.Visible = matchesSearch && matchesMatching;
        }
    }

    private bool MatchesMatching(
        IReadOnlyDictionary<EntProtoId<KinkDefinitionComponent>, KinkPreference> localKinks,
        IReadOnlyDictionary<EntProtoId<KinkDefinitionComponent>, KinkPreference> otherKinks,
        EntProtoId<KinkDefinitionComponent> kinkId)
    {
        var localPreference = localKinks.GetValueOrNullStruct(kinkId);
        var otherPreference = otherKinks.GetValueOrNullStruct(kinkId);
        return localPreference switch
        {
            KinkPreference.Favourite or KinkPreference.Yes when otherPreference >= KinkPreference.Yes => true,
            KinkPreference.No when otherPreference == KinkPreference.No => true,
            KinkPreference.Ask when otherPreference == KinkPreference.Ask => true,
            _ => false
        };
    }
}
