using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksControl : Control
{
    public bool DefaultToAsk;

    public KinksControl()
    {
        RobustXamlLoader.Load(this);
        SearchEdit.OnTextChanged += args => OnSearchChanged(args.Text);
    }

    public void ShowCategories()
    {
        ImportFlistButton.Visible = true;
        ImportFlistContainer.Visible = false;
        BackButton.Visible = false;
        MarkAllContainer.Visible = false;
        Categories.Visible = true;
        KinksContainer.Visible = false;
        SearchEdit.Text = string.Empty;
        FilterButtons(Categories, string.Empty);
    }

    public void ShowKinks()
    {
        ImportFlistButton.Visible = false;
        ImportFlistContainer.Visible = false;
        Categories.Visible = false;
        KinksContainer.Visible = true;
        BackButton.Visible = true;
        MarkAllContainer.Visible = true;
        SearchEdit.Text = string.Empty;
        FilterButtons(Kinks, string.Empty);
    }

    public void FilterButtons(Control control, string search)
    {
        foreach (var child in control.Children)
        {
            var text = child switch
            {
                Button { Text: not null } button => button.Text,
                KinksRow row => row.NameLabel.Text,
                _ => null
            };

            if (text == null)
                continue;

            child.Visible = string.IsNullOrWhiteSpace(search) ||
                            text.Contains(search, StringComparison.OrdinalIgnoreCase);
        }
    }

    public void OnSearchChanged(string search)
    {
        FilterButtons(Categories, search);
        FilterButtons(Kinks, search);
    }
}
