using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksEditingWindow : DefaultWindow
{
    public KinksEditingWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void ShowCategories()
    {
        Title = Loc.GetString("al-kinks");
        Control.ShowCategories();
    }
}
