using Content.Shared._Afterlight.Kinks;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Afterlight.Kinks.UI;

[GenerateTypedNameReferences]
public sealed partial class KinksListLabel : Control
{
    public EntProtoId<KinkDefinitionComponent>? KinkId { get; set; }

    public KinksListLabel()
    {
        RobustXamlLoader.Load(this);
    }
}
