using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Content.Client.Administration.Systems;
using Content.Shared.Administration;
using Content.Shared.Item;
using Content.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.Prototypes;
using Robust.Shared.IoC;
using Robust.Shared.Network;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        [Dependency] private readonly IPrototypeManager _prototype = default!;

        private readonly Action<string> _messageSender;

        // Admin-only context. When null, this is a player-facing panel and the
        // triage bar will never appear.
        private readonly NetUserId? _adminChannelId;

        // Cached so we don't re-classify the same string repeatedly.
        private string? _lastClassifiedText;
        private string? _lastClassifiedCategory;
        private string? _pendingUnstickPreviewOwner;
        private string? _pendingSaveShipPreviewOwner;
        private AssignDeedWindow? _assignDeedWindow;
        private bool _itemLookupBuilt;
        private int _itemLookupPrototypeCount = -1;
        private const int MaxCandidatesPerKeyword = 24;
        private readonly Dictionary<string, List<string>> _itemKeywordToPrototypes = new();
        private static readonly Regex ItemWordRegex = new("[A-Za-z0-9][A-Za-z0-9'_-]*", RegexOptions.Compiled);

        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        public event Action<string>? InputTextChanged;

        public BwoinkPanel(Action<string> messageSender) : this(messageSender, null)
        {
        }

        public BwoinkPanel(Action<string> messageSender, NetUserId? adminChannelId)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _messageSender = messageSender;
            _adminChannelId = adminChannelId;

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                    Unread = 0;
            };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;
            UpdateTypingIndicator();

            if (_adminChannelId is { } channel)
            {
                WireTriageBar(channel);
                // Show the always-on shortcuts (Player Panel / Inspect Ships / Snapshot)
                // immediately so admins don't have to wait for a classified message.
                ShowAlwaysOnShortcuts(channel);
            }
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            InputTextChanged?.Invoke(args.Text);
        }

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible)
                Unread++;

            var rendered = message.Text;
            // Only admins should see/trigger item mention links. Highlight in
            // both directions so admins can click items they themselves typed
            // when offering them to a player.
            if (_adminChannelId != null)
            {
                rendered = RenderItemMentions(message);
            }

            var formatted = new FormattedMessage(1);
            formatted.AddMarkupOrThrow($"[color=gray]{message.SentAt.ToShortTimeString()}[/color] {rendered}");
            TextOutput.AddMessage(formatted);
            LastMessage = message.SentAt;

            // Only classify regular player messages for this admin panel's channel.
            if (_adminChannelId != null && message.TrueSender == message.UserId)
                UpdateTriageBar(message.Text);
        }

        private void UpdateTypingIndicator()
        {
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);

            var text = PeopleTyping.Count == 0
                ? string.Empty
                : Loc.GetString("bwoink-system-typing-indicator",
                    ("players", string.Join(", ", PeopleTyping)),
                    ("count", PeopleTyping.Count));

            msg.AddText(text);
            msg.Pop();

            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name))
                    return;

                PeopleTyping.Add(name);
                Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed)
                        return;

                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else
            {
                PeopleTyping.Remove(name);
            }

            UpdateTypingIndicator();
        }

        // ---------- Triage shortcut bar ----------

        private void WireTriageBar(NetUserId channel)
        {
            try
            {
                var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                bwoinkSystem.AhelpAdminConfigUpdated += _ => RefreshTriageFromCache();
                bwoinkSystem.PlayerAhelpItemSpawned += OnPlayerAhelpItemSpawned;
                bwoinkSystem.PlayerShipInspectionReceived += OnPlayerShipInspectionReceived;
                bwoinkSystem.PlayerSnapshotReceived += OnPlayerSnapshotReceived;
                bwoinkSystem.PlayerBankInfoReceived += OnPlayerBankInfoReceived;
                bwoinkSystem.PlayerTeleportedToStation += OnPlayerTeleportedToStation;
                bwoinkSystem.PlayerTeleportedToShip += OnPlayerTeleportedToShip;
                bwoinkSystem.PlayerShipUnstickPreviewReceived += OnPlayerShipUnstickPreviewReceived;
                bwoinkSystem.PlayerShipUnstuck += OnPlayerShipUnstuck;
                bwoinkSystem.PlayerShipSavePreviewReceived += OnPlayerShipSavePreviewReceived;
                bwoinkSystem.PlayerShipSaved += OnPlayerShipSaved;
                bwoinkSystem.ShipDeedListReceived += OnShipDeedListReceived;
                bwoinkSystem.ShipDeedAssigned += OnShipDeedAssigned;
            }
            catch
            {
                // If system initialization fails, silently continue. The panel will still work,
                // just without the triage bar features. This is safe since the triage bar
                // initialization is not critical to the basic bwoink functionality.
            }
        }

        private void OnPlayerAhelpItemSpawned(SpawnAhelpItemResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow("AHelp Item Spawn");
            if (!response.Success)
            {
                var error = response.Error switch
                {
                    "not-authorized" => "Not authorized.",
                    "invalid-owner" => "Invalid player id.",
                    "invalid-prototype" => "Unknown item prototype.",
                    "not-item" => "Prototype is not an item.",
                    "offline" => "Player is offline.",
                    "no-attached-entity" => "Player has no attached entity.",
                    _ => "Failed to spawn item.",
                };
                window.AddMarkup($"[color=salmon]{FormattedMessage.EscapeText(error)}[/color]");
                window.OpenCentered();
                return;
            }

            var itemName = string.IsNullOrWhiteSpace(response.ItemName) ? response.PrototypeId : response.ItemName;
            window.AddMarkup($"Spawned [color=goldenrod]{FormattedMessage.EscapeText(itemName)}[/color] ([color=lightgray]{FormattedMessage.EscapeText(response.PrototypeId)}[/color]) at ({response.SpawnPosition.X:F0}, {response.SpawnPosition.Y:F0}).");
            window.OpenCentered();
        }

        private string RenderItemMentions(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!EnsureItemLookup())
                return message.Text;

            var split = message.Text.IndexOf(':');
            if (split < 0 || split >= message.Text.Length - 1)
                return message.Text;

            var bodyStart = split + 1;
            while (bodyStart < message.Text.Length && char.IsWhiteSpace(message.Text[bodyStart]))
            {
                bodyStart++;
            }

            if (bodyStart >= message.Text.Length)
                return message.Text;

            var prefix = message.Text[..bodyStart];
            var body = message.Text[bodyStart..];
            var ownerArg = message.UserId.UserId.ToString();

            var matches = ItemWordRegex.Matches(body);
            if (matches.Count == 0)
                return message.Text;

            var renderedBody = new StringBuilder(body.Length + 32);
            var cursor = 0;

            for (var index = 0; index < matches.Count;)
            {
                var maxLen = Math.Min(3, matches.Count - index);
                var bestLen = 0;
                string? bestKeyword = null;

                for (var len = maxLen; len >= 1; len--)
                {
                    if (!CanMergePhrase(matches, index, len, body))
                        continue;

                    var normalized = BuildMergedToken(matches, index, len);
                    if (!_itemKeywordToPrototypes.ContainsKey(normalized))
                        continue;

                    bestLen = len;
                    bestKeyword = normalized;
                    break;
                }

                if (bestLen == 0 || bestKeyword == null)
                {
                    index++;
                    continue;
                }

                var first = matches[index];
                var last = matches[index + bestLen - 1];
                var phraseStart = first.Index;
                var phraseEnd = last.Index + last.Length;

                if (phraseStart > cursor)
                    renderedBody.Append(body, cursor, phraseStart - cursor);

                var phraseText = body[phraseStart..phraseEnd];
                var safePhrase = FormattedMessage.EscapeText(phraseText);
                // Open a chooser even when the keyword resolves to a single
                // candidate so the admin always confirms which item they meant.
                var command = $"ahelpitemmenu {ownerArg} {bestKeyword}";
                // cmdlink uses the tag's Value as the rendered text, NOT inner text.
                // Correct form: [cmdlink="label" command="cmd"/]
                renderedBody.Append($"[cmdlink=\"{safePhrase}\" command=\"{command}\"/]");

                cursor = phraseEnd;
                index += bestLen;
            }

            if (cursor < body.Length)
                renderedBody.Append(body, cursor, body.Length - cursor);

            return prefix + renderedBody;
        }

        private static bool CanMergePhrase(MatchCollection matches, int start, int len, string source)
        {
            for (var i = start; i < start + len - 1; i++)
            {
                var current = matches[i];
                var next = matches[i + 1];
                var gapStart = current.Index + current.Length;
                var gapLength = next.Index - gapStart;

                if (gapLength < 0)
                    return false;

                for (var g = 0; g < gapLength; g++)
                {
                    var ch = source[gapStart + g];
                    if (!char.IsWhiteSpace(ch) && ch != '-' && ch != '_')
                        return false;
                }
            }

            return true;
        }

        private static string BuildMergedToken(MatchCollection matches, int start, int len)
        {
            var sb = new StringBuilder();
            for (var i = start; i < start + len; i++)
            {
                var normalized = NormalizeItemToken(matches[i].Value);
                if (normalized.Length > 0)
                    sb.Append(normalized);
            }

            return sb.ToString();
        }

        private bool EnsureItemLookup()
        {
            var currentProtoCount = _prototype.Count<EntityPrototype>();
            if (_itemLookupBuilt &&
                _itemLookupPrototypeCount == currentProtoCount &&
                _itemKeywordToPrototypes.Count > 0)
            {
                return true;
            }

            _itemLookupPrototypeCount = currentProtoCount;
            _itemKeywordToPrototypes.Clear();
            AhelpItemMentionRegistry.Clear();

            foreach (var proto in _prototype.EnumeratePrototypes<EntityPrototype>())
            {
                if (proto.Abstract || !IsItemPrototype(proto))
                    continue;

                AddItemKeyword(proto.ID, proto.ID);
                AddItemKeyword(proto.Name, proto.ID);

                if (!string.IsNullOrWhiteSpace(proto.EditorSuffix))
                    AddItemKeyword(proto.EditorSuffix, proto.ID);
            }

            foreach (var (keyword, ids) in _itemKeywordToPrototypes)
                AhelpItemMentionRegistry.Set(keyword, ids);

            _itemLookupBuilt = _itemKeywordToPrototypes.Count > 0;
            return _itemLookupBuilt;
        }

        private bool IsItemPrototype(EntityPrototype proto)
        {
            if (proto.HasComponent<ItemComponent>())
                return true;

            if (proto.Parents == null || proto.Parents.Length == 0)
                return false;

            var seen = new HashSet<string> { proto.ID };
            var queue = new Queue<string>(proto.Parents);

            while (queue.TryDequeue(out var parentId))
            {
                if (!seen.Add(parentId))
                    continue;

                if (!_prototype.TryIndex(parentId, out var parent))
                    continue;

                if (parent.HasComponent<ItemComponent>())
                    return true;

                if (parent.Parents == null || parent.Parents.Length == 0)
                    continue;

                foreach (var grandParent in parent.Parents)
                {
                    queue.Enqueue(grandParent);
                }
            }

            return false;
        }

        private void AddItemKeyword(string key, string prototypeId)
        {
            if (string.IsNullOrWhiteSpace(key))
                return;

            var normalized = NormalizeItemToken(key);
            AddItemKeywordAlias(normalized, prototypeId);

            var tokens = ExtractKeywordTokens(key);
            if (tokens.Count > 0)
                AddItemKeywordAlias(tokens[^1], prototypeId);

            if (tokens.Count >= 2)
            {
                var lastTwo = tokens[^2] + tokens[^1];
                AddItemKeywordAlias(lastTwo, prototypeId);

                // Some IDs encode "MagBoots" as "...BootsMag"; support both orders.
                if (tokens[^1].Length <= 4)
                {
                    var reversed = tokens[^1] + tokens[^2];
                    AddItemKeywordAlias(reversed, prototypeId);
                }
            }
        }

        private void AddItemKeywordAlias(string normalized, string prototypeId)
        {
            if (normalized.Length < 3)
                return;

            if (!_itemKeywordToPrototypes.TryGetValue(normalized, out var bucket))
            {
                bucket = new List<string>();
                _itemKeywordToPrototypes[normalized] = bucket;
            }

            if (bucket.Count >= MaxCandidatesPerKeyword || bucket.Contains(prototypeId))
                return;

            bucket.Add(prototypeId);
        }

        private static List<string> ExtractKeywordTokens(string source)
        {
            var tokens = new List<string>();
            var sb = new StringBuilder();
            var previousWasLower = false;

            void Flush()
            {
                if (sb.Length == 0)
                    return;

                var token = sb.ToString();
                sb.Clear();

                if (token.Length >= 3)
                    tokens.Add(token);
            }

            foreach (var ch in source)
            {
                if (!char.IsLetterOrDigit(ch))
                {
                    Flush();
                    previousWasLower = false;
                    continue;
                }

                if (char.IsLetter(ch) && char.IsUpper(ch) && previousWasLower)
                    Flush();

                var lowered = char.ToLowerInvariant(ch);
                sb.Append(lowered);
                previousWasLower = char.IsLower(lowered);
            }

            Flush();
            return tokens;
        }

        private static string NormalizeItemToken(string token)
        {
            var sb = new StringBuilder(token.Length);
            foreach (var ch in token)
            {
                if (char.IsLetterOrDigit(ch))
                    sb.Append(char.ToLowerInvariant(ch));
            }

            return sb.ToString();
        }

        private void OnPlayerShipInspectionReceived(PlayerShipInspectionResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            // Match this panel's channel (server returns the OwnerUserId we sent).
            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-ships-title"));

            if (!string.IsNullOrEmpty(response.Error))
            {
                window.AddMarkup($"[color=salmon]{Loc.GetString("bwoink-triage-ship-inspect-error")}[/color]");
                window.OpenCentered();
                return;
            }

            if (response.Ships.Length == 0)
            {
                window.AddMarkup($"[color=lightgray]{Loc.GetString("bwoink-triage-ship-inspect-none")}[/color]");
                window.OpenCentered();
                return;
            }

            window.AddMarkup($"[color=goldenrod]{Loc.GetString("bwoink-triage-ship-inspect-header", ("count", response.Ships.Length))}[/color]");

            foreach (var ship in response.Ships)
            {
                var displayName = string.IsNullOrEmpty(ship.Suffix) ? ship.Name : $"{ship.Name} ({ship.Suffix})";
                var ftlChip = ship.InFtl
                    ? $"[color=orange]FTL: {ship.FtlState}[/color]"
                    : $"[color=lightgreen]FTL: {ship.FtlState}[/color]";
                var onlineChip = ship.OwnerOnline
                    ? "[color=lightgreen]online[/color]"
                    : "[color=salmon]offline[/color]";
                var voucherChip = ship.PurchasedWithVoucher ? " [color=cyan](voucher)[/color]" : string.Empty;
                window.AddMarkup(
                    $"  [color=white]{displayName}[/color]{voucherChip} — {ship.MapName} @ ({ship.WorldPosition.X:F0}, {ship.WorldPosition.Y:F0}) — {ftlChip} — owner {onlineChip}");
            }

            window.OpenCentered();
        }

        private void RefreshTriageFromCache()
        {
            if (Disposed || _adminChannelId is null)
                return;

            // If the cached message no longer classifies under the new config, hide.
            if (_lastClassifiedText is { } text)
                UpdateTriageBar(text, force: true);
        }

        private void UpdateTriageBar(string messageText, bool force = false)
        {
            if (_adminChannelId is not { } channel)
                return;

            if (!force && string.Equals(_lastClassifiedText, messageText, StringComparison.Ordinal))
                return;

            _lastClassifiedText = messageText;

            var bwoinkSystem = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            var category = AhelpCategoryClassifier.Classify(messageText, bwoinkSystem.CurrentAhelpAdminConfig);

            if (category is null)
            {
                if (_lastClassifiedCategory != null)
                {
                    _lastClassifiedCategory = null;
                    ShowAlwaysOnShortcuts(channel);
                }
                return;
            }

            // Skip rebuilding buttons if the category didn't change.
            if (_lastClassifiedCategory == category)
                return;

            _lastClassifiedCategory = category;
            RenderTriageBar(channel, category);
        }

        private void ShowAlwaysOnShortcuts(NetUserId channel)
        {
            // Neutral label when no message has classified yet.
            var label = new FormattedMessage();
            label.PushColor(Color.LightGray);
            label.AddText(Loc.GetString("bwoink-triage-suggested-prefix"));
            label.Pop();
            TriageCategoryLabel.SetMessage(label);

            TriageActionContainer.RemoveAllChildren();
            AddAlwaysOnShortcuts(channel);
            TriageBar.Visible = true;
        }

        private void AddAlwaysOnShortcuts(NetUserId channel)
        {
            var console = IoCManager.Resolve<IClientConsoleHost>();
            var channelArg = $"\"{channel}\"";

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-player-panel"),
                () => console.ExecuteCommand($"playerpanel {channelArg}")));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-inspect-ships"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestPlayerShipInspection(channel);
                }));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-snapshot"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestPlayerSnapshot(channel);
                }));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-banking"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestPlayerBankInfo(channel);
                }));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-unstick-ship"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    _pendingUnstickPreviewOwner = channel.UserId.ToString();
                    system.RequestUnstickPlayerShipPreview(channel);
                }));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-tp-station"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestTeleportPlayerToStation(channel);
                }));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-tp-ship"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestTeleportPlayerToShip(channel);
                }));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-assign-deed"),
                () => OpenAssignDeedWindow(channel)));

            TriageActionContainer.AddChild(MakeShortcutButton(
                Loc.GetString("bwoink-triage-action-save-ship"),
                () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    _pendingSaveShipPreviewOwner = channel.UserId.ToString();
                    system.RequestSaveShipPreview(channel);
                }));
        }

        private void RenderTriageBar(NetUserId channel, string category)
        {
            // Label
            var label = new FormattedMessage();
            label.PushColor(Color.LightGray);
            label.AddText(Loc.GetString("bwoink-triage-suggested-prefix"));
            label.AddText(" ");
            label.Pop();
            label.PushColor(Color.Goldenrod);
            label.AddText(category);
            label.Pop();
            TriageCategoryLabel.SetMessage(label);

            // Buttons
            TriageActionContainer.RemoveAllChildren();
            AddAlwaysOnShortcuts(channel);

            var console = IoCManager.Resolve<IClientConsoleHost>();
            var channelArg = $"\"{channel}\"";

            // Category-specific shortcuts. Mapping is intentionally conservative;
            // each shortcut points to a command that is known to exist server-side.
            foreach (var extra in GetCategoryShortcuts(category))
            {
                var localized = Loc.GetString(extra.LocaleKey);
                var command = extra.CommandFactory(channelArg);
                TriageActionContainer.AddChild(MakeShortcutButton(localized,
                    () => console.ExecuteCommand(command)));
            }

            TriageBar.Visible = true;
        }

        private static Button MakeShortcutButton(string text, Action onPressed)
        {
            var button = new Button
            {
                Text = text,
                StyleClasses = { "OpenLeft" },
            };
            button.OnPressed += _ => onPressed();
            return button;
        }

        private readonly record struct TriageShortcut(string LocaleKey, Func<string, string> CommandFactory);

        private void OnPlayerSnapshotReceived(PlayerSnapshotResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-snapshot-title"));

            if (!string.IsNullOrEmpty(response.Error) || response.Snapshot is null)
            {
                window.AddMarkup($"[color=salmon]{Loc.GetString("bwoink-triage-snapshot-error")}[/color]");
                window.OpenCentered();
                return;
            }

            var s = response.Snapshot;
            window.AddMarkup($"[color=goldenrod]{Loc.GetString("bwoink-triage-snapshot-header")}[/color]");

            var statusChip = s.Online ? "[color=lightgreen]online[/color]" : "[color=salmon]offline[/color]";
            var mindChip = s.HasMind ? "[color=lightgreen]has mind[/color]" : "[color=salmon]no mind[/color]";
            var detachedChip = s.DetachedFromBody ? " [color=orange](detached from body)[/color]" : string.Empty;
            var attachedDisplay = string.IsNullOrEmpty(s.AttachedEntityName) ? "—" : s.AttachedEntityName;

            window.AddMarkup($"  status: {statusChip}, {mindChip}{detachedChip}");
            window.AddMarkup($"  attached: [color=white]{attachedDisplay}[/color]");
            window.AddMarkup($"  location: {s.MapName} @ ({s.WorldPosition.X:F0}, {s.WorldPosition.Y:F0})");

            if (s.Roles.Length > 0)
                window.AddMarkup($"  roles: [color=cyan]{string.Join(", ", s.Roles)}[/color]");

            window.OpenCentered();
        }

        private static IEnumerable<TriageShortcut> GetCategoryShortcuts(string category)
        {
            // Match against the well-known default category names. Custom categories
            // get just the always-on Player Panel button.
            switch (category.Trim().ToLowerInvariant())
            {
                case "respawn":
                    yield return new TriageShortcut(
                        "bwoink-triage-action-respawn",
                        arg => $"respawn {arg}");
                    break;
                case "stuck":
                case "lost":
                    yield return new TriageShortcut(
                        "bwoink-triage-action-follow",
                        arg => $"follow {arg}");
                    break;
                case "harassment":
                case "grief":
                    yield return new TriageShortcut(
                        "bwoink-triage-action-notes",
                        arg => $"adminnotes {arg}");
                    break;
            }
        }

        private void OnPlayerBankInfoReceived(PlayerBankInfoResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            if (!string.IsNullOrEmpty(response.Error))
            {
                var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-banking-title"));
                window.AddMarkup($"[color=salmon]{Loc.GetString("bwoink-triage-banking-error")}[/color]");
                window.OpenCentered();
                return;
            }

            // Create banking management window
            var bankingWindow = new BankingManagementWindow(
                channel.UserId.ToString(),
                channel,
                response.Balance);
            bankingWindow.OpenCentered();
        }

        private void OnPlayerShipUnstuck(UnstickPlayerShipResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-unstick-title"));
            if (response.Success)
            {
                window.AddMarkup(Loc.GetString("bwoink-unstick-success",
                    ("ship", response.ShipName ?? "Unknown"),
                    ("x", (int)response.NewPosition.X),
                    ("y", (int)response.NewPosition.Y)));
            }
            else
            {
                var errKey = response.Error switch
                {
                    "not-authorized" => "bwoink-unstick-error-not-authorized",
                    "empty-owner" => "bwoink-unstick-error-empty-owner",
                    "no-ship" => "bwoink-unstick-error-no-ship",
                    "in-ftl" => "bwoink-unstick-error-in-ftl",
                    "no-position" => "bwoink-unstick-error-no-position",
                    "no-clear-spot" => "bwoink-unstick-error-no-clear-spot",
                    "ftl-failed" => "bwoink-unstick-error-ftl-failed",
                    _ => "bwoink-unstick-error-generic",
                };
                window.AddMarkup($"[color=salmon]{Loc.GetString(errKey)}[/color]");
            }
            window.OpenCentered();
        }

        private void OnPlayerShipUnstickPreviewReceived(UnstickPlayerShipPreviewResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            if (!string.Equals(_pendingUnstickPreviewOwner, response.OwnerUserId, StringComparison.Ordinal))
                return;

            _pendingUnstickPreviewOwner = null;

            if (!response.Success)
            {
                var errKey = response.Error switch
                {
                    "not-authorized" => "bwoink-unstick-error-not-authorized",
                    "empty-owner" => "bwoink-unstick-error-empty-owner",
                    "no-ship" => "bwoink-unstick-error-no-ship",
                    _ => "bwoink-unstick-error-generic",
                };

                var failWindow = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-unstick-title"));
                failWindow.AddMarkup($"[color=salmon]{Loc.GetString(errKey)}[/color]");
                failWindow.OpenCentered();
                return;
            }

            var shipName = string.IsNullOrWhiteSpace(response.ShipName) ? "Unknown" : response.ShipName;
            var confirmWindow = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-unstick-title"));
            confirmWindow.AddMarkup(Loc.GetString("bwoink-unstick-confirm", ("ship", shipName)));
            confirmWindow.AddActionButton(Loc.GetString("bwoink-unstick-confirm-button"), () =>
            {
                var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                system.RequestUnstickPlayerShip(channel);
            }, closeOnPressed: true);
            confirmWindow.OpenCentered();
        }

        private void OnPlayerShipSavePreviewReceived(SaveShipPreviewResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            if (!string.Equals(_pendingSaveShipPreviewOwner, response.OwnerUserId, StringComparison.Ordinal))
                return;

            _pendingSaveShipPreviewOwner = null;

            if (!response.Success)
            {
                var errKey = response.Error switch
                {
                    "not-authorized" => "bwoink-save-ship-error-not-authorized",
                    "empty-owner" => "bwoink-save-ship-error-empty-owner",
                    "no-ship" => "bwoink-save-ship-error-no-ship",
                    _ => "bwoink-save-ship-error-generic",
                };

                var failWindow = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-save-ship-title"));
                failWindow.AddMarkup($"[color=salmon]{Loc.GetString(errKey)}[/color]");
                failWindow.OpenCentered();
                return;
            }

            var shipName = string.IsNullOrWhiteSpace(response.ShipName) ? "Unknown" : response.ShipName;
            var confirmSaveWindow = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-save-ship-title"));
            confirmSaveWindow.AddMarkup(Loc.GetString("bwoink-save-ship-confirm", ("ship", shipName)));
            confirmSaveWindow.AddActionButton(Loc.GetString("bwoink-save-ship-confirm-button"), () =>
            {
                var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                system.RequestSaveShip(channel);
            }, closeOnPressed: true);
            confirmSaveWindow.OpenCentered();
        }

        private void OnPlayerShipSaved(SaveShipResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-save-ship-title"));
            if (response.Success)
            {
                window.AddMarkup(Loc.GetString("bwoink-save-ship-success",
                    ("ship", response.ShipName ?? "Unknown"),
                    ("evicted", response.EvictedCount)));
            }
            else
            {
                var errKey = response.Error switch
                {
                    "not-authorized" => "bwoink-save-ship-error-not-authorized",
                    "invalid-owner" => "bwoink-save-ship-error-invalid-owner",
                    "no-ship" => "bwoink-save-ship-error-no-ship",
                    "owner-offline" => "bwoink-save-ship-error-owner-offline",
                    "save-failed" => "bwoink-save-ship-error-save-failed",
                    _ => "bwoink-save-ship-error-generic",
                };
                window.AddMarkup($"[color=salmon]{Loc.GetString(errKey)}[/color]");
            }
            window.OpenCentered();
        }

        private void OnPlayerTeleportedToStation(TeleportPlayerToStationResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-tp-station-title"));
            if (response.Success)
            {
                window.AddMarkup(Loc.GetString("bwoink-tp-station-success",
                    ("destination", response.DestinationName ?? "Station"),
                    ("x", (int)response.DestinationPosition.X),
                    ("y", (int)response.DestinationPosition.Y)));
            }
            else
            {
                var errKey = response.Error switch
                {
                    "not-authorized" => "bwoink-tp-station-error-not-authorized",
                    "invalid-owner" => "bwoink-tp-station-error-invalid-owner",
                    "offline" => "bwoink-tp-station-error-offline",
                    "no-attached-entity" => "bwoink-tp-station-error-no-attached-entity",
                    "no-station" => "bwoink-tp-station-error-no-station",
                    "no-arrivals" => "bwoink-tp-station-error-no-arrivals",
                    _ => "bwoink-tp-station-error-generic",
                };
                window.AddMarkup($"[color=salmon]{Loc.GetString(errKey)}[/color]");
            }

            window.OpenCentered();
        }

        private void OpenAssignDeedWindow(NetUserId channel)
        {
            if (_assignDeedWindow == null || _assignDeedWindow.Disposed || !_assignDeedWindow.IsOpen)
            {
                _assignDeedWindow = new AssignDeedWindow(channel.UserId.ToString());
                _assignDeedWindow.OnClose += () => _assignDeedWindow = null;
                _assignDeedWindow.RefreshRequested += () =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestShipDeedList(channel);
                };
                _assignDeedWindow.AssignRequested += ship =>
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestAssignShipDeed(channel, ship.ShipNetEntity);
                };
                _assignDeedWindow.OpenCentered();
            }
            else
            {
                _assignDeedWindow.MoveToFront();
            }

            // Always request a fresh list when opening / focusing.
            var bwoinkSys = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
            bwoinkSys.RequestShipDeedList(channel);
        }

        private void OnShipDeedListReceived(ShipDeedListResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.TargetUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            _assignDeedWindow?.UpdateShipList(response.Ships);
        }

        private void OnShipDeedAssigned(AssignShipDeedResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.TargetUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            if (_assignDeedWindow != null && !_assignDeedWindow.Disposed)
            {
                var msg = response.Success
                    ? Loc.GetString("bwoink-assign-deed-success", ("ship", response.ShipName ?? "the ship"))
                    : Loc.GetString(response.Error switch
                    {
                        "not-authorized" => "bwoink-assign-deed-error-not-authorized",
                        "invalid-owner" => "bwoink-assign-deed-error-invalid-owner",
                        "offline" => "bwoink-assign-deed-error-offline",
                        "no-attached-entity" => "bwoink-assign-deed-error-no-attached-entity",
                        "no-id-card" => "bwoink-assign-deed-error-no-id-card",
                        "no-ship" => "bwoink-assign-deed-error-no-ship",
                        _ => "bwoink-assign-deed-error-generic",
                    });
                _assignDeedWindow.ShowStatus(response.Success, msg);

                // Refresh the list after a successful assign so the new ownership shows.
                if (response.Success)
                {
                    var system = IoCManager.Resolve<IEntityManager>().System<BwoinkSystem>();
                    system.RequestShipDeedList(channel);
                }
            }
        }

        private void OnPlayerTeleportedToShip(TeleportPlayerToShipResponseMessage response)
        {
            if (Disposed || _adminChannelId is not { } channel)
                return;

            if (!string.Equals(response.OwnerUserId, channel.UserId.ToString(), StringComparison.Ordinal))
                return;

            var window = new TriageInfoWindow(Loc.GetString("bwoink-triage-popup-tp-ship-title"));
            if (response.Success)
            {
                window.AddMarkup(Loc.GetString("bwoink-tp-ship-success",
                    ("ship", response.ShipName ?? "their ship"),
                    ("x", (int)response.DestinationPosition.X),
                    ("y", (int)response.DestinationPosition.Y)));
            }
            else
            {
                var errKey = response.Error switch
                {
                    "not-authorized" => "bwoink-tp-ship-error-not-authorized",
                    "invalid-owner" => "bwoink-tp-ship-error-invalid-owner",
                    "offline" => "bwoink-tp-ship-error-offline",
                    "no-attached-entity" => "bwoink-tp-ship-error-no-attached-entity",
                    "no-ship" => "bwoink-tp-ship-error-no-ship",
                    "in-ftl" => "bwoink-tp-ship-error-in-ftl",
                    "no-safe-tile" => "bwoink-tp-ship-error-no-safe-tile",
                    _ => "bwoink-tp-ship-error-generic",
                };
                window.AddMarkup($"[color=salmon]{Loc.GetString(errKey)}[/color]");
            }

            window.OpenCentered();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            InputTextChanged = null;
        }
    }
}
