using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Log;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        private readonly Button _createNewCharacterButton;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);

            // HardLight: Self-heal if this GUI is constructed before prefs arrive.
            // Without this, ReloadCharacterPickers silently early-returns to an empty
            // list (see the ServerDataLoaded check below) and there is no other trigger
            // to repaint short of toggling LobbyGui.SwitchState or restarting the client.
            _preferencesManager.OnServerDataLoaded += OnPreferencesLoaded;
        }

        private void OnPreferencesLoaded()
        {
            if (Disposed)
                return;
            // Only repaint if we're actually visible in the tree AND the picker
            // is currently empty -- avoids redundantly racing with
            // LobbyUIController.PreferencesDataLoaded, which also triggers a
            // ReloadCharacterPickers on this same event.
            if (Parent == null)
                return;
            if (Characters.ChildCount > 0)
                return;
            ReloadCharacterPickers();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _preferencesManager.OnServerDataLoaded -= OnPreferencesLoaded;
            base.Dispose(disposing);
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.DisposeAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                numberOfFullSlots++;

                // HardLight: isolate each picker construction. If one profile is corrupt
                // (e.g. invalid species/loadout/company prototype) and CharacterPickerButton's
                // constructor throws, we used to lose every subsequent slot, leaving only the
                // first character visible. Skip the broken slot instead.
                CharacterPickerButton characterPickerButton;
                try
                {
                    characterPickerButton = new CharacterPickerButton(_entManager,
                        _protomanager,
                        characterButtonsGroup,
                        character,
                        slot == selectedSlot);
                }
                catch (Exception e)
                {
                    Logger.GetSawmill("lobby").Error($"Failed to build character picker for slot {slot}: {e}");
                    continue;
                }

                Characters.AddChild(characterPickerButton);

                var capturedSlot = slot;
                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(capturedSlot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(capturedSlot);
                };
            }

            _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
        }
    }
}
