using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Shared._TE.Laws.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Laws.Ui;

[GenerateTypedNameReferences]
public sealed partial class LawArticleEditorPanel : Control
{
    public event Action? PublishButtonPressed;
    public event Action<string>? ArticleDraftUpdated;

    private bool _preview;

    public LawArticleEditorPanel()
    {
        RobustXamlLoader.Load(this);

        ButtonPublish.StyleClasses.Add(StyleBase.ButtonOpenLeft);
        ButtonPublish.StyleClasses.Add(StyleNano.StyleClassButtonColorGreen);

        ContentField.GetChild(0).Margin = new Thickness(9, 3);
        // Customize scrollbar width and margin. This is not possible in xaml
        var scrollbar = ContentField.GetChild(1);
        scrollbar.SetWidth = 6f;
        scrollbar.Margin = new Thickness(9, 0, 2 , 0);

        ButtonPreview.OnPressed += OnPreview;
        ButtonCancel.OnPressed += OnCancel;
        ButtonPublish.OnPressed += OnPublish;
        ButtonSaveDraft.OnPressed += OnDraftSaved;

        ContentField.OnTextChanged += args => OnTextChanged(Rope.CalcTotalLength(args.TextRope), args.Control, SharedLawsSystem.MaxContentLength);
    }

    private void OnTextChanged(long length, Control control, long maxLength)
    {
        if (length > maxLength)
        {
            control.ModulateSelfOverride = Color.Red;
            control.ToolTip = Loc.GetString("laws-writer-text-length-exceeded");

            ButtonPublish.Disabled = true;
            ButtonPreview.Disabled = true;
        }
        else
        {
            control.ModulateSelfOverride = null;
            control.ToolTip = string.Empty;

            ButtonPublish.Disabled = false;
            ButtonPreview.Disabled = false;
        }

        // save draft regardless; they can edit down the length later
        ArticleDraftUpdated?.Invoke(Rope.Collapse(ContentField.TextRope));
    }

    private void OnPreview(BaseButton.ButtonEventArgs eventArgs)
    {
        _preview = !_preview;

        TextEditPanel.Visible = !_preview;
        PreviewPanel.Visible = _preview;
        PreviewLabel.SetMarkupPermissive(Rope.Collapse(ContentField.TextRope));
    }

    private void OnCancel(BaseButton.ButtonEventArgs eventArgs)
    {
        Reset();
        Visible = false;
    }

    private void OnPublish(BaseButton.ButtonEventArgs eventArgs)
    {
        PublishButtonPressed?.Invoke();
        Reset();
        Visible = false;
    }

    private void OnDraftSaved(BaseButton.ButtonEventArgs eventArgs)
    {
        ArticleDraftUpdated?.Invoke(Rope.Collapse(ContentField.TextRope));
        Visible = false;
    }

    private void Reset()
    {
        _preview = false;
        TextEditPanel.Visible = true;
        PreviewPanel.Visible = false;
        PreviewLabel.SetMarkup("");
        ContentField.TextRope = Rope.Leaf.Empty;
        ArticleDraftUpdated?.Invoke(string.Empty);
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        ButtonPreview.OnPressed -= OnPreview;
        ButtonCancel.OnPressed -= OnCancel;
        ButtonPublish.OnPressed -= OnPublish;
    }
}
