- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  setPreference: true
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Research
  - Maintenance
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      multiplier: 3
    - type: InnatePsionicPowers
      powersToAdd:
        - TelepathyPower
        - HealingWordPower

- type: startingGear
  id: ChaplainGear
  equipment:
#    shoes: ClothingShoesColorBlack # HL - Add NF-style departmental loadouts
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain
  inhand:
    - STextImplanter
