using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class ServerTab : Control
    {
        [Dependency] private readonly IConfigurationManager _config = default!;

        private static readonly (string Title, string Body, string Yes, string No)[] ShutdownSteps =
        {
            (
                "Shutdown Server",
                "Are you sure you want to shut down the server?\nAll players will be disconnected.",
                "Yes, shut it down",
                "No, cancel"
            ),
            (
                "Are You SURE Sure?",
                "This will end the round for everyone.\nThe clown hasn't even had a chance to honk yet.\n\nReally shut it down?",
                "Yes, end their suffering",
                "Wait, let the clown honk"
            ),
            (
                "HOLD ON",
                "There are real people playing right now.\nSome of them are probably doing something very important,\nlike being a clown.\n\nHave you considered... NOT shutting it down?",
                "Confirmed. I am heartless.",
                "You know what, fair point"
            ),
            (
                "This Is Your Last Warning",
                "The server AI is watching you.\nCentral Command is watching you.\nThe lawyer is watching you.\n\nAll logs will show: YOU did this.\nAre you ABSOLUTELY certain?",
                "I accept full responsibility",
                "I am not paid enough for this"
            ),
            (
                "FINAL CONFIRMATION",
                "By clicking confirm you agree to:\n\n  - Take full responsibility for this round ending\n  - Personally apologize to every clown on the server\n  - File a NT-47 Incident Report in triplicate\n  - Accept that the HoP is nowhere near their desk\n    and nobody is getting job changes approved\n\nThe command is shown below.\nCopy it and run it in the server console yourself.",
                "Fine. Show me the command.",
                "I have changed my mind. Again."
            ),
        };

        private const string ShutdownCaptchaPhrase = "HONK SAFETY 1212";

        public ServerTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _config.OnValueChanged(CCVars.OocEnabled, OocEnabledChanged, true);
            _config.OnValueChanged(CCVars.LoocEnabled, LoocEnabledChanged, true);

            ShutdownButton.OnPressed += _ => ShowShutdownStep(0);
        }

        private void ShowShutdownStep(int step)
        {
            var (title, body, yes, no) = ShutdownSteps[step];

            var window = new DefaultWindow
            {
                Title = title,
                MinSize = new System.Numerics.Vector2(440, 10),
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 10,
                Margin = new Thickness(16),
            };

            root.AddChild(new Label
            {
                Text = body,
                ClipText = false,
            });

            var buttons = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };

            var yesBtn = new Button { Text = yes, HorizontalExpand = true };
            var noBtn  = new Button { Text = no,  HorizontalExpand = true };

            var isFinal = step == ShutdownSteps.Length - 1;

            yesBtn.OnPressed += _ =>
            {
                window.Close();
                if (!isFinal)
                    ShowShutdownStep(step + 1);
                else
                    ShowShutdownCaptcha();
            };

            noBtn.OnPressed += _ => window.Close();

            buttons.AddChild(yesBtn);
            buttons.AddChild(noBtn);
            root.AddChild(buttons);

            window.Contents.AddChild(root);
            window.OpenCentered();
        }

        private static void ShowShutdownCaptcha()
        {
            var window = new DefaultWindow
            {
                Title = "Final Security CAPTCHA",
                MinSize = new System.Numerics.Vector2(460, 10),
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 10,
                Margin = new Thickness(16),
            };

            root.AddChild(new Label
            {
                Text = "Nanotrasen Safety Compliance Check\n\nTo proceed, type the exact phrase below:\n\n" + ShutdownCaptchaPhrase,
                ClipText = false,
            });

            var captchaInput = new LineEdit
            {
                PlaceHolder = "Type phrase exactly",
                HorizontalExpand = true,
            };
            root.AddChild(captchaInput);

            var status = new Label
            {
                Text = "",
                StyleClasses = { "LabelSubText" },
            };
            root.AddChild(status);

            var buttons = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
            };

            var verifyBtn = new Button
            {
                Text = "Verify CAPTCHA",
                HorizontalExpand = true,
            };
            var cancelBtn = new Button
            {
                Text = "Cancel",
                HorizontalExpand = true,
            };

            verifyBtn.OnPressed += _ =>
            {
                var pass = string.Equals(captchaInput.Text.Trim(), ShutdownCaptchaPhrase, System.StringComparison.OrdinalIgnoreCase);
                if (!pass)
                {
                    status.Text = "CAPTCHA failed. The clown union thanks you for trying.";
                    return;
                }

                window.Close();
                ShowShutdownCommand();
            };

            cancelBtn.OnPressed += _ => window.Close();

            buttons.AddChild(verifyBtn);
            buttons.AddChild(cancelBtn);
            root.AddChild(buttons);

            window.Contents.AddChild(root);
            window.OpenCentered();
        }

        private static void ShowShutdownCommand()
        {
            const string cmd = "shutdown";

            var window = new DefaultWindow
            {
                Title = "Server Shutdown Command",
                MinSize = new System.Numerics.Vector2(440, 10),
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 10,
                Margin = new Thickness(16),
            };

            root.AddChild(new Label
            {
                Text = "Run this in the server console to shut down:",
            });

            root.AddChild(new LineEdit
            {
                Text = cmd,
                Editable = false,
                HorizontalExpand = true,
            });

            root.AddChild(new Label
            {
                Text = "We're not doing it for you. You know what you did.",
                StyleClasses = { "LabelSubText" },
            });

            var closeBtn = new Button
            {
                Text = "Close",
                HorizontalAlignment = HAlignment.Right,
            };
            closeBtn.OnPressed += _ => window.Close();
            root.AddChild(closeBtn);

            window.Contents.AddChild(root);
            window.OpenCentered();
        }

        private void OocEnabledChanged(bool value)
        {
            SetOocButton.Pressed = value;
        }

        private void LoocEnabledChanged(bool value)
        {
            SetLoocButton.Pressed = value;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _config.UnsubValueChanged(CCVars.OocEnabled, OocEnabledChanged);
                _config.UnsubValueChanged(CCVars.LoocEnabled, LoocEnabledChanged);
            }
        }
    }
}
