# HardLight: Commented out due to not currently being used.
# - type: department
#   id: UnionOfSovietSocialistPlanets
#   name: department-UnionOfSovietSocialistPlanets
#   description: department-UnionOfSovietSocialistPlanets-description
#   color: "#B01340"
