- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  setPreference: true # Frontier
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 18000 # 5 hrs
  - !type:DepartmentTimeRequirement
    department: Science
    time: 36000 # 10 hrs
  weight: 30 # HardLight: 10<30
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  requireAdminNotify: true
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  - Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: PsionicBonusChance # Nyano: Makes it more likely to become psionic.
      flatBonus: 1
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
