using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.MobInteraction;

[GenerateTypedNameReferences]
public sealed partial class ALMobInteractionWindow : DefaultWindow
{
    public ALMobInteractionWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

