using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Afterlight.MobInteraction;

[GenerateTypedNameReferences]
public sealed partial class ALMobInteractionPreferenceButton : Button
{
    public ALMobInteractionPreferenceButton()
    {
        RobustXamlLoader.Load(this);
    }
}
